server:
  port: 8082

spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    com.dkghosh.inventoryservice: INFO
  # ===== FILE LOGGING CONFIG (disabled) =====
# logging:
#   file:
#     name: logs/${spring.application.name}.log
#   level:
#     root: INFO
#     com.dkghosh.inventoryservice: INFO
#     org.springframework.kafka: INFO